### ISSUE TITLE
Loading SP3 

### ISSUE THREAD

**Issue by Babs-s6** [spanikp/GNSS-toolbox#15]
Hello, 
first of all, thank you for your time and effort in making this toolbox which is really interesting. 
I am new to the coding world, so treat me as someone who doesn't know anything related to coding, but i really need to use your toolbox in my studies. and i would appreciate it if i am allowed to do that and i will acknowledge all your work. 

I am trying to load SP3 file i downloaded from [cddis.gsfc.nasa.gov](url) but i dont know which file i should open and put the directory to.
[sio07006.zip](https://github.com/spanikp/GNSS-toolbox/files/7560157/sio07006.zip)

Again, thank you for your time.

**Comment by spanikp** [comment]
Hello @Babs-s6 thanks for your interest in GNSS-toolbox. I checked the file you provided and I has to say that so far I do not come to contact with such old ephemeris data :) It seems that file is actually one of early SP3 formats (version of first line is even not set). I find out document which could be helpful http://epncb.oma.be/ftp/data/format/sp1.pdf for full specification. GNSS-toolbox does not provide support for such format, but I could implement support for it. Do you really need to process such old data - from year 1993? Time interval of position is also a bit tricky - it is 1350 second (22.5 minutes). GNSS-toolbox implements 10th order Lagrange interpolation for precise ephemeris data, but it require data sampling interval to be 15 minutes, so this will also require adjustment.
