### ISSUE TITLE
Error using downloadBroadcastMessage (line 89) \n7-Zip application not found!\nPlease install before continue or provide unzipped navigation

### ISSUE THREAD

**Issue by SepidehAbadpour** [spanikp/GNSS-toolbox#9]
I get the error while 7-zip application is installed on my machine

**Comment by SepidehAbadpour** [comment]
I have added the path to user variables and system variables. while I myself run `7z --help` on commandline, I get:

    C:\WINDOWS\system32>7z --help

    7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

    Usage: 7z <command> [<switches>...] <archive_name> [<file_names>...] [@listfile]

    <Commands>
      a : Add files to archive
      b : Benchmark
      d : Delete files from archive
      e : Extract files from archive (without using directory names)
      h : Calculate hash values for files
      i : Show information about supported formats
      l : List contents of archive
      rn : Rename files in archive
      t : Test integrity of archive
      u : Update files to archive
      x : eXtract files with full paths

    <Switches>
      -- : Stop switches and @listfile parsing
      -ai[r[-|0]]{@listfile|!wildcard} : Include archives
      -ax[r[-|0]]{@listfile|!wildcard} : eXclude archives
      -ao{a|s|t|u} : set Overwrite mode
      -an : disable archive_name field
      -bb[0-3] : set output log level
      -bd : disable progress indicator
      -bs{o|e|p}{0|1|2} : set output stream for output/error/progress line
      -bt : show execution time statistics
      -i[r[-|0]]{@listfile|!wildcard} : Include filenames
      -m{Parameters} : set compression Method
        -mmt[N] : set number of CPU threads
        -mx[N] : set compression level: -mx1 (fastest) ... -mx9 (ultra)
      -o{Directory} : set Output directory
      -p{Password} : set Password
      -r[-|0] : Recurse subdirectories
      -sa{a|e|s} : set Archive name mode
      -scc{UTF-8|WIN|DOS} : set charset for for console input/output
      -scs{UTF-8|UTF-16LE|UTF-16BE|WIN|DOS|{id}} : set charset for list files
      -scrc[CRC32|CRC64|SHA1|SHA256|*] : set hash function for x, e, h commands
      -sdel : delete files after compression
      -seml[.] : send archive by email
      -sfx[{name}] : Create SFX archive
      -si[{name}] : read data from stdin
      -slp : set Large Pages mode
      -slt : show technical information for l (List) command
      -snh : store hard links as links
      -snl : store symbolic links as links
      -sni : store NT security information
      -sns[-] : store NTFS alternate streams
      -so : write data to stdout
      -spd : disable wildcard matching for file names
      -spe : eliminate duplication of root folder for extract command
      -spf : use fully qualified file paths
      -ssc[-] : set sensitive case mode
      -sse : stop archive creating, if it can't open some input file
      -ssw : compress shared files
      -stl : set archive timestamp from the most recently modified file
      -stm{HexMask} : set CPU thread affinity mask (hexadecimal number)
      -stx{Type} : exclude archive type
      -t{Type} : Set type of archive
      -u[-][p#][q#][r#][x#][y#][z#][!newArchiveName] : Update options
      -v{Size}[b|k|m|g] : Create volumes
      -w[{path}] : assign Work directory. Empty path means a temporary directory
      -x[r[-|0]]{@listfile|!wildcard} : eXclude filenames
      -y : assume Yes on all queries

The issue is with line [89 of the file downloadBroadcastMessage.m](https://github.com/spanikp/GNSS-toolbox/blob/819d42eda0f5397a5cd57e6dfa2e4683db4b0997/src/loading-utils/rnx-nav/downloadBroadcastMessage.m#L89)

**Comment by spanikp** [comment]
This is strange, since once the `7z` app is added to system path MATLAB should be able to run it via `system` command.
Does command `7z --help` work also from different directory than in `C:\WINDOWS\system32`?

**Comment by SepidehAbadpour** [comment]
Thanks for your answer.
The problem is solved. [I needed to restart my machine](https://stackoverflow.com/a/65034140/1245120)
By the way your code is really useful. I like your object oriented approach. 
A fantastic clean code and understandable for another programmer!!!

**Comment by spanikp** [comment]
Thank you :) It is great you find it useful. If you would like to extend some functionality, pull requests are welcome!
